-- ============================================================
-- MOTIVA VERDE - SPRINT 03
-- Script de criação do banco de dados
-- Oracle Database
-- ============================================================


-- ============================================================
-- 1. EQUIPE DE MANUTENÇÃO
-- Baseada na classe EquipeManutencao
-- ============================================================

CREATE TABLE TB_EQUIPE_MANUTENCAO (
    ID_EQUIPE NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME VARCHAR2(100) NOT NULL,
    ESPECIALIDADE VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_EQUIPE_MANUTENCAO
        PRIMARY KEY (ID_EQUIPE)
);


-- ============================================================
-- 2. TRECHO DE RODOVIA
-- Baseada nas classes TrechoRodovia e TrechoMonitorado
-- ============================================================

CREATE TABLE TB_TRECHO_RODOVIA (
    ID_TRECHO NUMBER GENERATED BY DEFAULT AS IDENTITY,
    QUILOMETRO NUMBER NOT NULL,
    ALTURA_VEGETACAO NUMBER(6,2) NOT NULL,
    CONDICAO_CRESCIMENTO VARCHAR2(30) NOT NULL,
    ID_EQUIPE NUMBER,

    TIPO_TRECHO VARCHAR2(20) DEFAULT 'RODOVIA' NOT NULL,
    CODIGO_SENSOR VARCHAR2(50),

    CONSTRAINT PK_TRECHO_RODOVIA
        PRIMARY KEY (ID_TRECHO),

    CONSTRAINT FK_TRECHO_EQUIPE
        FOREIGN KEY (ID_EQUIPE)
        REFERENCES TB_EQUIPE_MANUTENCAO (ID_EQUIPE),

    CONSTRAINT CK_CONDICAO_CRESCIMENTO
        CHECK (
            CONDICAO_CRESCIMENTO IN (
                'BAIXO_CRESCIMENTO',
                'CRESCIMENTO_MODERADO',
                'ALTO_CRESCIMENTO'
            )
        ),

    CONSTRAINT CK_TIPO_TRECHO
        CHECK (
            TIPO_TRECHO IN (
                'RODOVIA',
                'MONITORADO'
            )
        )
);


-- ============================================================
-- 3. INTERVENÇÃO OPERACIONAL
-- Baseada em IntervencaoOperacional,
-- RocadaMecanizada e Pulverizacao
-- ============================================================

CREATE TABLE TB_INTERVENCAO_OPERACIONAL (
    ID_INTERVENCAO NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_TRECHO NUMBER NOT NULL,
    TIPO_INTERVENCAO VARCHAR2(30) NOT NULL,
    DATA_EXECUCAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ALTURA_ANTES NUMBER(6,2),
    ALTURA_DEPOIS NUMBER(6,2),

    CONSTRAINT PK_INTERVENCAO_OPERACIONAL
        PRIMARY KEY (ID_INTERVENCAO),

    CONSTRAINT FK_INTERVENCAO_TRECHO
        FOREIGN KEY (ID_TRECHO)
        REFERENCES TB_TRECHO_RODOVIA (ID_TRECHO),

    CONSTRAINT CK_TIPO_INTERVENCAO
        CHECK (
            TIPO_INTERVENCAO IN (
                'ROCADA_MECANIZADA',
                'PULVERIZACAO'
            )
        )
);


-- ============================================================
-- 4. RELATÓRIO DE PRIORIDADE
-- Histórico dos relatórios gerados pelo sistema
-- ============================================================

CREATE TABLE TB_RELATORIO_PRIORIDADE (
    ID_RELATORIO NUMBER GENERATED BY DEFAULT AS IDENTITY,
    DATA_GERACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    QT_BAIXA NUMBER DEFAULT 0 NOT NULL,
    QT_MODERADA NUMBER DEFAULT 0 NOT NULL,
    QT_ALTA NUMBER DEFAULT 0 NOT NULL,
    QT_URGENTE NUMBER DEFAULT 0 NOT NULL,

    RESUMO VARCHAR2(1000),

    CONSTRAINT PK_RELATORIO_PRIORIDADE
        PRIMARY KEY (ID_RELATORIO)
);