CREATE SEQUENCE SEQ_EQUIPE_MANUTENCAO
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_TRECHO_RODOVIA
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_INTERVENCAO_OPERACIONAL
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_RELATORIO_PRIORIDADE
    START WITH 1000
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;